export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const CINEMA_ROUTE = '/cinema'
export const BASKET_ROUTE = '/basket'
export const CONTENT_ROUTE = '/content'